<a href="https://colab.research.google.com/github/davidsadovy/data690_fall2022/blob/main/assignment_07/assignment_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import required libraries
import pandas as pd
import plotly.express as px

In [2]:
# read csv data file from web address into a dataframe
df = pd.read_csv("https://raw.githubusercontent.com/wcj365/python-stats-dataviz/master/assignments/assignment_07_world_dev/world_devlopment_indicator.csv")

# explore shape of dataframe
df.shape

(34954, 9)

In [3]:
# explore random sample of dataframe
df.sample(5)

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
14762,14762,1985,60.877,SP.DYN.LE00.IN,IRQ,Iraq,Middle East & North Africa,Upper middle income,IBRD
23392,23392,2011,7348328.000,SP.POP.TOTL,BGR,Bulgaria,Europe & Central Asia,Upper middle income,IBRD
19526,19526,1970,64.097,SP.DYN.LE00.IN,LKA,Sri Lanka,South Asia,Lower middle income,IBRD
26520,26520,1987,8332446.000,SP.POP.TOTL,GTM,Guatemala,Latin America & Caribbean,Upper middle income,IBRD
6813,6813,2000,2.000,SH.STA.SUIC.P5,CYP,Cyprus,Europe & Central Asia,High income,Not classified

In [4]:
# select countries to examine
# 2 countries in which I've been stationed: NLD, KOR
# 2 countries that I've visited: AUS, SWE
my_countries = ["NLD", "KOR", "AUS", "SWE"]

# create new dataframe with just my selected countries
df2 = df[df["Country Code"].isin(my_countries)]

# explore shape of dataframe
df2.shape

(700, 9)

In [6]:
# explore random sample of dataframe
df2.sample(5)

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
7719,7719,2006,23.7,SH.STA.SUIC.P5,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified
30174,30174,1986,14572278.0,SP.POP.TOTL,NLD,Netherlands,Europe & Central Asia,High income,Not classified
33132,33132,1968,7912273.0,SP.POP.TOTL,SWE,Sweden,Europe & Central Asia,High income,Not classified
22216,22216,2013,23128129.0,SP.POP.TOTL,AUS,Australia,East Asia & Pacific,High income,Not classified
28024,28024,2003,47892330.0,SP.POP.TOTL,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified

In [7]:
# confirm unique country names in dataframe
df2["Country Name"].unique()

array(['Australia', 'Korea, Rep.', 'Netherlands', 'Sweden'], dtype=object)

In [8]:
# explore first 5 lines of dataframe
df2.head()

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
242,242,1990,17367.110580,NY.GDP.PCAP.PP.CD,AUS,Australia,East Asia & Pacific,High income,Not classified
243,243,1991,17822.475281,NY.GDP.PCAP.PP.CD,AUS,Australia,East Asia & Pacific,High income,Not classified
244,244,1992,18214.597871,NY.GDP.PCAP.PP.CD,AUS,Australia,East Asia & Pacific,High income,Not classified
245,245,1993,19159.521590,NY.GDP.PCAP.PP.CD,AUS,Australia,East Asia & Pacific,High income,Not classified
246,246,1994,20094.054111,NY.GDP.PCAP.PP.CD,AUS,Australia,East Asia & Pacific,High income,Not classified

In [9]:
# explore last 5 lines of dataframe
df2.tail()

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
33181,33181,2017,10057698.0,SP.POP.TOTL,SWE,Sweden,Europe & Central Asia,High income,Not classified
33182,33182,2018,10175214.0,SP.POP.TOTL,SWE,Sweden,Europe & Central Asia,High income,Not classified
33183,33183,2019,10278887.0,SP.POP.TOTL,SWE,Sweden,Europe & Central Asia,High income,Not classified
33184,33184,2020,10353442.0,SP.POP.TOTL,SWE,Sweden,Europe & Central Asia,High income,Not classified
33185,33185,2021,10415811.0,SP.POP.TOTL,SWE,Sweden,Europe & Central Asia,High income,Not classified

In [10]:
# create new dataframe with just population in my selected countries for 2021 (latest year available)
df3 = df2.query('indicator == "SP.POP.TOTL" and Year == 2021')

df3

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
22224,22224,2021,25739256.0,SP.POP.TOTL,AUS,Australia,East Asia & Pacific,High income,Not classified
28042,28042,2021,51744876.0,SP.POP.TOTL,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified
30209,30209,2021,17533405.0,SP.POP.TOTL,NLD,Netherlands,Europe & Central Asia,High income,Not classified
33185,33185,2021,10415811.0,SP.POP.TOTL,SWE,Sweden,Europe & Central Asia,High income,Not classified

In [11]:
# compare population in my selected countries in 2021 using bar chart
fig = px.bar(
    df3, 
    x="Country Name", 
    y="value", 
    title="2021 Population of Australia, Republic of South Korea, Netherlands, and Sweden", 
    color="Country Name", 
    template="presentation"
    )

# lendend is redundant, so remove it
fig.update_layout(showlegend=False)

fig.show()

In [12]:
# compare population in my selected countries in 2021 using pie chart
fig = px.pie(
    df3, 
    names="Country Name", 
    values="value",
    title="2021 Population of Australia, Republic of South Korea, Netherlands, and Sweden", 
    color="Country Name", 
    template="seaborn"
    )

# lendend is redundant, so remove it
fig.update_layout(showlegend=False)

fig.update_traces(textposition='inside', textinfo='label+value+percent')

fig.show()

In [13]:
# create new dataframe with just population in my selected countries for all avaiable years
df4 = df2.query('indicator == "SP.POP.TOTL"')

# explore first 5 rows of dataframe
df4.head()

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
22163,22163,1960,10276477.0,SP.POP.TOTL,AUS,Australia,East Asia & Pacific,High income,Not classified
22164,22164,1961,10483000.0,SP.POP.TOTL,AUS,Australia,East Asia & Pacific,High income,Not classified
22165,22165,1962,10742000.0,SP.POP.TOTL,AUS,Australia,East Asia & Pacific,High income,Not classified
22166,22166,1963,10950000.0,SP.POP.TOTL,AUS,Australia,East Asia & Pacific,High income,Not classified
22167,22167,1964,11167000.0,SP.POP.TOTL,AUS,Australia,East Asia & Pacific,High income,Not classified

In [14]:
# compare population of my selected countries for all available years using line chart
fig = px.line(
    df4, 
    x="Year",
    y="value", 
    title="Population of Australia, Republic of South Korea, Netherlands, and Sweden from 1960-2021", 
    color="Country Name", 
    template="ggplot2"
    )

fig.show()

In [16]:
# explore unique indicator names
df["indicator"].unique()

array(['NY.GDP.PCAP.PP.CD', 'SH.STA.SUIC.P5', 'SP.DYN.LE00.IN',
       'SP.POP.TOTL'], dtype=object)

In [28]:
# select indicators for Life Expectancy and GDP Per Capita
my_indicators = ['SP.DYN.LE00.IN', 'NY.GDP.PCAP.PP.CD']

# create new dataframe with just the selected indicators for all countries
df5 = df[df["indicator"].isin(my_indicators)]

# explore shape of dataframe
df5.shape

(17883, 9)

In [18]:
# explore random sample of dataframe
df5.sample(10)

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
20433,20433,1979,66.364000,SP.DYN.LE00.IN,TTO,Trinidad and Tobago,Latin America & Caribbean,High income,IBRD
3202,3202,2001,1360.063690,NY.GDP.PCAP.PP.CD,MDG,Madagascar,Sub-Saharan Africa,Low income,IDA
19293,19293,1981,45.068000,SP.DYN.LE00.IN,SOM,Somalia,Sub-Saharan Africa,Low income,IDA
12839,12839,1972,55.586000,SP.DYN.LE00.IN,SLV,El Salvador,Latin America & Caribbean,Lower middle income,IBRD
20791,20791,1971,62.099000,SP.DYN.LE00.IN,ARE,United Arab Emirates,Middle East & North Africa,High income,Not classified
13136,13136,1964,40.810000,SP.DYN.LE00.IN,ETH,Ethiopia,Sub-Saharan Africa,Low income,IDA
14722,14722,2006,72.257000,SP.DYN.LE00.IN,IRN,"Iran, Islamic Rep.",Middle East & North Africa,Lower middle income,IBRD
13486,13486,1972,48.793000,SP.DYN.LE00.IN,GAB,Gabon,Sub-Saharan Africa,Upper middle income,IBRD
10831,10831,1994,55.878000,SP.DYN.LE00.IN,BTN,Bhutan,South Asia,Lower middle income,IDA
2014,2014,1994,22784.581469,NY.GDP.PCAP.PP.CD,DEU,Germany,Europe & Central Asia,High income,Not classified

In [19]:
# reduce dataframe to keep only columns of interest
df5 = df5[["Year", "value", "indicator", "Country Code", "Country Name"]]

# explore random sample of dataframe
df5.sample(5)

       Year       value          indicator Country Code  Country Name
12986  1997   53.548000     SP.DYN.LE00.IN          ERI       Eritrea
16942  1962   65.061902     SP.DYN.LE00.IN          MNE    Montenegro
4688   2000  692.224607  NY.GDP.PCAP.PP.CD          SLE  Sierra Leone
19017  2017   53.895000     SP.DYN.LE00.IN          SLE  Sierra Leone
13913  1990   69.598000     SP.DYN.LE00.IN          GRD       Grenada

In [20]:
# create new dataframe with indicators as separate columns
df6 = pd.pivot_table(df5, values="value", index=["Country Code", "Country Name", "Year"], columns="indicator").reset_index()

# explore first 5 rows of dataframe
df6.head()

indicator Country Code Country Name  Year  NY.GDP.PCAP.PP.CD  SP.DYN.LE00.IN
0                  ABW        Aruba  1960                NaN          65.662
1                  ABW        Aruba  1961                NaN          66.074
2                  ABW        Aruba  1962                NaN          66.444
3                  ABW        Aruba  1963                NaN          66.787
4                  ABW        Aruba  1964                NaN          67.113

In [21]:
# rename indicator columns
df6 = df6.rename(columns={'NY.GDP.PCAP.PP.CD': 'GDP Per Capita', 'SP.DYN.LE00.IN': 'Life Expectancy'})

# explore first 5 rows of dataframe
df6.head()

indicator Country Code Country Name  Year  GDP Per Capita  Life Expectancy
0                  ABW        Aruba  1960             NaN           65.662
1                  ABW        Aruba  1961             NaN           66.074
2                  ABW        Aruba  1962             NaN           66.444
3                  ABW        Aruba  1963             NaN           66.787
4                  ABW        Aruba  1964             NaN           67.113

In [22]:
# clean dataframe by dropping rows without valid data
df6.dropna(inplace=True)

# explore first 5 rows of dataframe
df6.head()

indicator Country Code Country Name  Year  GDP Per Capita  Life Expectancy
30                 ABW        Aruba  1990    21942.267486           73.468
31                 ABW        Aruba  1991    23554.172809           73.509
32                 ABW        Aruba  1992    24156.033900           73.544
33                 ABW        Aruba  1993    24978.226168           73.573
34                 ABW        Aruba  1994    26089.472258           73.598

In [26]:
# create scatter plot showing health vs wealth for all countries in 2020
fig = px.scatter(
    df6.query('Year == 2020'), 
    x="GDP Per Capita",
    y="Life Expectancy", 
    title="Wealth vs Health", 
    color="Country Name", 
    template="plotly_dark"
    )

# lendend is redundant, so remove it
fig.update_layout(showlegend=False)

fig.show()

## Group By

df.groupby([group]).agg(agg functions)

agg functions can be sum, mean, count, median.

https://realpython.com/pandas-groupby/

In [60]:
# create new dataframe with just the population for all countries in 2021
df7 = df.query('indicator == "SP.POP.TOTL" and Year == 2021')

# explore shape of dataframe
df7.shape

(216, 9)

In [61]:
# explore the first 5 rows of the dataframe
df7.head()

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
21604,21604,2021,39835428.0,SP.POP.TOTL,AFG,Afghanistan,South Asia,Low income,IDA
21666,21666,2021,2811666.0,SP.POP.TOTL,ALB,Albania,Europe & Central Asia,Upper middle income,IBRD
21728,21728,2021,44616626.0,SP.POP.TOTL,DZA,Algeria,Middle East & North Africa,Lower middle income,IBRD
21790,21790,2021,55103.0,SP.POP.TOTL,ASM,American Samoa,East Asia & Pacific,Upper middle income,Not classified
21852,21852,2021,77354.0,SP.POP.TOTL,AND,Andorra,Europe & Central Asia,High income,Not classified

In [62]:
df8 = df7.groupby(["Region"]).sum()

df8

                            Unnamed: 0    Year         value
Region
East Asia & Pacific            1078331   74777  2.345135e+09
Europe & Central Asia          1631824  117218  9.237537e+08
Latin America & Caribbean      1163829   84882  6.580892e+08
Middle East & North Africa      613375   42441  4.724950e+08
North America                    81043    6063  3.702037e+08
South Asia                      217038   16168  1.877902e+09
Sub-Saharan Africa             1328271   94987  1.161963e+09

In [63]:
# rename indicator columns
df8 = df8.rename(columns={'value': '2021 Population, total (group sum)'})

# explore first 5 rows of dataframe
df8

,Unnamed: 0,Year,"2021 Population, total (group sum)"
Region,,,
East Asia & Pacific,1078331,74777,2.345135e+09
Europe & Central Asia,1631824,117218,9.237537e+08
Latin America & Caribbean,1163829,84882,6.580892e+08
Middle East & North Africa,613375,42441,4.724950e+08
North America,81043,6063,3.702037e+08
South Asia,217038,16168,1.877902e+09
Sub-Saharan Africa,1328271,94987,1.161963e+09

In [66]:
df8 = df8.sort_values(by="2021 Population, total (group sum)")

df8

,Unnamed: 0,Year,"2021 Population, total (group sum)"
Region,,,
North America,81043,6063,3.702037e+08
Middle East & North Africa,613375,42441,4.724950e+08
Latin America & Caribbean,1163829,84882,6.580892e+08
Europe & Central Asia,1631824,117218,9.237537e+08
Sub-Saharan Africa,1328271,94987,1.161963e+09
South Asia,217038,16168,1.877902e+09
East Asia & Pacific,1078331,74777,2.345135e+09

In [71]:
# compare population in my selected countries in 2021 using bar chart
fig = px.bar(
    df7, 
    x="Region", 
    y="2021 Population, total (group sum)", 
    title="2021 Population by Region", 
    color="Region", 
    template="plotly_dark"
    )

# lendend is redundant, so remove it
fig.update_layout(showlegend=False)

fig.show()

ValueError: ignored